endpoint = "0.0.0.0:3000"
node_endpoint = "http://127.0.0.1:1420"
graphana_endpoint = "http://127.0.0.1:3000"
temp_command = "/usr/bin/python3 mock-temp.py"
ppa_command = "/usr/bin/python3 mock-ppa.py"
# Seconds between reporting
reporting_interval = 120.0
raum_id = 6
